version: '3'
services:

  web:
    image: nginx
    ports:
      - "8085:80"
    container_name: myweb

  db:
    image: mysql
    container_name: mydb
    environment:
      MYSQL_ROOT_PASSWORD: root